"""empty message

Revision ID: 081390a5d05c
Revises: d990a62f5e4a
Create Date: 2020-08-09 00:08:27.256633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081390a5d05c'
down_revision = 'd990a62f5e4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genre')
    # ### end Alembic commands ###
