"""empty message

Revision ID: a18a3c0337a9
Revises: d7f9c961bf70
Create Date: 2020-09-07 15:45:51.798971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a18a3c0337a9'
down_revision = 'd7f9c961bf70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('category_id', sa.Integer(), nullable=True))
    # Copy from category to category_id
    op.execute('UPDATE questions SET category_id = category;')
    op.create_foreign_key(None, 'questions', 'categories', ['category_id'], ['id'])
    op.drop_column('questions', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.execute('UPDATE questions SET category = category_id;')
    op.drop_column('questions', 'category_id')
    # ### end Alembic commands ###
